Repository andes/andes-test-integracion, pull requests merged in 2020-09, with the labels that each got.

#222 feat(rup): add inicio prestacion
  cypress/plugins/seed-prestaciones.js
Labels: fix

#223 refactor: agrega nuevos plex autocompletado
  cypress/support/index.d.ts
Labels: enhancement

#234 MPI: se corrige test en auditoría
  cypress/integration/apps/auditoria/auditoria.spec.js
Labels: test ok

#233 MPI - agrega hora nacimiento en alta de bebe
  cypress/integration/apps/citas/turnos/turnos.spec.js
  cypress/integration/core/mpi/mpi-registro-bebe.spec.js
Labels: test ok

#236 feat(top): Quita wizard que se reemplazo por hint
  cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js
  cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js
  cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js
  cypress/integration/apps/solicitud/solicitudes.spec.js
Labels: test ok

#238 Fix editar agenda
  cypress/integration/apps/citas/agendas/gestor_agenda.spec.js
Labels: test ok

#229 test: check errors
  cypress/integration/apps/rup/internacion/epicrisis.spec.js
  cypress/support/index.js
Labels: test ok

#240 feat(huds): nuevas rutas
  cypress/integration/apps/rup/punto-inicio/punto-inicio-navegacion.spec.js
  cypress/integration/apps/rup/punto-inicio/punto-inicio-sidebar.spec.js
  data/modulos/modulos_basic.json
Labels: test ok

#212 TOP-79
  cypress/fixtures/agendasClonar/agendaOriginal.json
  cypress/fixtures/apps/citas/agendaDarSobreturno.json
  cypress/fixtures/apps/citas/agendas/gestor-agendas-listado/agendaMedicinaGeneralAPublicar.json
  cypress/fixtures/apps/citas/agendas/gestor-agendas-listado/agendaMedicinaGeneralPublicada.json
  cypress/integration/apps/buscador-prestaciones-turnos/buscador-prestaciones-turnos.spec.js
  cypress/integration/apps/citas/agendas/planificacion_agendas.spec.js
  cypress/integration/apps/gestor-usuarios/perfiles.spec.js
  cypress/integration/apps/solicitud/liberarTurnoSolicitud.spec.js
  cypress/integration/apps/solicitud/nuevaSolicitudEntrada.spec.js
  cypress/integration/apps/solicitud/nuevaSolicitudSalida.spec.js
  cypress/integration/apps/solicitud/solicitudes.spec.js
  data/conceptoTurneable/conceptoTurneable_basic.json
Labels: test ok

#218 MPI - Refactor auditoria
  cypress/integration/apps/auditoria/auditoria.spec.js
  cypress/integration/apps/auditoria/reportarError.spec.js
  cypress/plugins/seed-paciente.js
Labels: test ok

#245 fix(TOP): agrega condicion para controlar fin de mes
  cypress/integration/apps/solicitud/darTurnoSolicitud.spec.js
Labels: test ok
