Repository andes/andes-test-integracion, pull requests merged in 2023-08, with the labels that each got.

#484 fix(QUERIES): corrige filtro en visualizacion de informacion
  cypress/e2e/apps/visualizacion-informacion/bi-queries.spec.js
Labels: test fail

#483 Se corrigen test varios
  cypress/e2e/apps/perinatal/control-alertas.spec.ts
  cypress/e2e/core/mpi/mpi-registro-bebe.spec.ts
  cypress/support/index.d.ts
  cypress/support/plex.js
Labels: test ok

#480 IN - Control anular internación
  cypress/support/mapa-camas.js
Labels: test ok, prioritario
